version: '3.8'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./:/usr/src/app # ローカルをコンテナ内にマウント
    command: "yarn start"
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 8g